### Register a New User
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "John Doe",
    "password": "password123",
    "mail": "eM2dR@example.com"
}

### Login with the New User
POST http://localhost:3000/login
Content-Type: application/json

{
    "mail": "eM2dR@example.com",
    "password": "password123"
}

### Logout
GET http://localhost:3000/logout

### Protected Route
GET http://localhost:3000/protected

### 
GET http://localhost:3000/user/bedirhan
###
GET http://localhost:3000/show/tv/30984
###
GET http://localhost:3000/search?query=Naruto&is_movie=false

### 
GET http://localhost:3000/show/movie/438631
