### Register a New User
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "John Doe",
    "password": "password123",
    "mail": "eM2dR@example.com"
}

### Login with the New User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "mail": "eM2dR@example.com",
    "password": "password123"
}

### Logout
GET http://localhost:3000/auth/logout

### Protected Route
GET http://localhost:3000/protected

### 
GET http://localhost:3000/user/info
Content-Type: application/json

{
    "username": "John Doe"
}

###
GET http://localhost:3000/show/info?type=tv&show_id=1247

### 
GET http://localhost:3000/show/info?type=movie&show_id=438631

###
GET http://localhost:3000/show/search?query=Naruto&type=tv
